# Generated by Django 6.0.3 on 2026-03-24 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'course_offering', 'date')},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='at_risk_threshold',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='threshold_warnings_enabled',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='warning_threshold',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='weekly_reports_enabled',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.courseoffering'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('absent', 'Absent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.section'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.programme'),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.programme'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='session_type',
        ),
    ]
